services:
  php:
    image: php:8.2-apache
    container_name: booksearch-php
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html/backend
      - ./frontend:/var/www/html/frontend
    depends_on:
      - mysql
    command: >
      bash -c "docker-php-ext-install mysqli pdo pdo_mysql && apache2-foreground"

  mysql:
    image: mysql:8
    container_name: booksearch-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./backend/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: booksearch-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpass

volumes:
  dbdata:
